version: '2.4'
services:
  postgres:
    container_name: postgres
    image: postgres:14.7
    ports:
       - "5432:5432"
    environment:
      PGPORT: 5432
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'homework-9'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "8180:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@localhost.local
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres